In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('countries.csv')

In [4]:
columns = df.columns
columns

Index(['Country', 'ESTJ-A', 'ESFJ-A', 'INFP-T', 'ESFJ-T', 'ENFP-T', 'ENFP-A',
       'ESTJ-T', 'ISFJ-T', 'ENFJ-A', 'ESTP-A', 'ISTJ-A', 'INTP-T', 'INFJ-T',
       'ISFP-T', 'ENTJ-A', 'ESTP-T', 'ISTJ-T', 'ESFP-T', 'ENTP-A', 'ESFP-A',
       'INTJ-T', 'ISFJ-A', 'INTP-A', 'ENTP-T', 'ISTP-T', 'ENTJ-T', 'ISTP-A',
       'INFP-A', 'ENFJ-T', 'INTJ-A', 'ISFP-A', 'INFJ-A'],
      dtype='object')

In [5]:
#get the combine mbti types
mbti_types = sorted(set(col.split('-')[0] for col in df.columns if '-' in col))

In [8]:
combined_data = pd.DataFrame(columns=['Country'] + mbti_types)

In [12]:
combined_data

,Country,ENFJ,ENFP,ENTJ,ENTP,ESFJ,ESFP,ESTJ,ESTP,INFJ,INFP,INTJ,INTP,ISFJ,ISFP,ISTJ,ISTP
0,Afghanistan,0.0562,0.0796,0.0511,0.0495,0.1006,0.0527,0.1188,0.0652,0.0463,0.0686,0.0431,0.0549,0.0610,0.0460,0.0629,0.0434
1,Albania,0.0775,0.1045,0.0686,0.0792,0.0665,0.0405,0.0667,0.0381,0.0748,0.1045,0.0604,0.0754,0.0449,0.0334,0.0418,0.0233
2,Algeria,0.0556,0.0857,0.0535,0.0739,0.0440,0.0279,0.0327,0.0241,0.0800,0.1556,0.0896,0.1410,0.0337,0.0377,0.0320,0.0330
3,Andorra,0.1163,0.1767,0.0465,0.0372,0.0651,0.0372,0.0605,0.0187,0.0791,0.1674,0.0326,0.0512,0.0465,0.0419,0.0279,0.0186
4,Angola,0.0807,0.0798,0.0492,0.0448,0.1192,0.0547,0.0592,0.0368,0.0771,0.1112,0.0466,0.0564,0.0717,0.0403,0.0404,0.0322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Vanuatu,0.0795,0.1297,0.0126,0.0503,0.0837,0.1046,0.0670,0.0210,0.0837,0.1213,0.0335,0.0293,0.0627,0.0753,0.0377,0.0210
154,Vietnam,0.0666,0.1193,0.0282,0.0428,0.1024,0.0656,0.0481,0.0291,0.0615,0.1447,0.0297,0.0550,0.0732,0.0718,0.0342,0.0279
155,Yemen,0.0689,0.1188,0.0498,0.0690,0.0642,0.0565,0.0594,0.0325,0.0556,0.1101,0.0546,0.0929,0.0479,0.0383,0.0459,0.0354
156,Zambia,0.0726,0.0983,0.0435,0.0445,0.1253,0.0559,0.0630,0.0264,0.0800,0.0977,0.0426,0.0533,0.0819,0.0542,0.0406,0.0203
157,Zimbabwe,0.0837,0.1134,0.0486,0.0526,0.1134,0.0505,0.0584,0.0272,0.0761,0.1111,0.0383,0.0516,0.0741,0.0436,0.0372,0.0204

In [14]:
combined_data['Country'] = df['Country']
for mbti_type in mbti_types:
    combined_data[mbti_type] = df.filter(regex=f'^{mbti_type}-').sum(axis=1)

In [15]:
max_mbti_per_country = combined_data.groupby('Country').idxmax(axis=1)
prop_max_per_country = combined_data.drop(columns='Country').max(axis=1)

In [16]:
result = max_mbti_per_country.reset_index().drop(columns='level_1')
result['Proportion'] = prop_max_per_country.apply(lambda x: "{:.4f}".format(x))
result.rename(columns={0: 'MBTI_type'}, inplace=True)
result['Percentage'] = (result['Proportion'].astype(float) * 100).apply(lambda x: "{:.2f}%".format(x))

In [17]:
result['MBTI_type'].unique()

array(['ESTJ', 'ENFP', 'INFP', 'ESFJ', 'ISFJ'], dtype=object)

In [18]:
result

         Country MBTI_type Proportion Percentage
0    Afghanistan      ESTJ     0.1188     11.88%
1        Albania      ENFP     0.1045     10.45%
2        Algeria      INFP     0.1556     15.56%
3        Andorra      ENFP     0.1767     17.67%
4         Angola      ESFJ     0.1192     11.92%
..           ...       ...        ...        ...
153      Vanuatu      ENFP     0.1297     12.97%
154      Vietnam      INFP     0.1447     14.47%
155        Yemen      ENFP     0.1188     11.88%
156       Zambia      ESFJ     0.1253     12.53%
157     Zimbabwe      ENFP     0.1134     11.34%

[158 rows x 4 columns]

In [25]:
columns_to_format = combined_data.columns[1:]
combined_data_numeric = combined_data[columns_to_format].apply(pd.to_numeric, errors='coerce')
formatted_data = combined_data_numeric.applymap(lambda x: "{:.4f}".format(x))

In [30]:
formatted_data['Country'] =result['Country']
formatted_data

,ENFJ,ENFP,ENTJ,ENTP,ESFJ,ESFP,ESTJ,ESTP,INFJ,INFP,INTJ,INTP,ISFJ,ISFP,ISTJ,ISTP,Country
0,0.0562,0.0796,0.0511,0.0495,0.1006,0.0527,0.1188,0.0652,0.0463,0.0686,0.0431,0.0549,0.0610,0.0460,0.0629,0.0434,Afghanistan
1,0.0775,0.1045,0.0686,0.0792,0.0665,0.0405,0.0667,0.0381,0.0748,0.1045,0.0604,0.0754,0.0449,0.0334,0.0418,0.0233,Albania
2,0.0556,0.0857,0.0535,0.0739,0.0440,0.0279,0.0327,0.0241,0.0800,0.1556,0.0896,0.1410,0.0337,0.0377,0.0320,0.0330,Algeria
3,0.1163,0.1767,0.0465,0.0372,0.0651,0.0372,0.0605,0.0187,0.0791,0.1674,0.0326,0.0512,0.0465,0.0419,0.0279,0.0186,Andorra
4,0.0807,0.0798,0.0492,0.0448,0.1192,0.0547,0.0592,0.0368,0.0771,0.1112,0.0466,0.0564,0.0717,0.0403,0.0404,0.0322,Angola
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,0.0795,0.1297,0.0126,0.0503,0.0837,0.1046,0.0670,0.0210,0.0837,0.1213,0.0335,0.0293,0.0627,0.0753,0.0377,0.0210,Vanuatu
154,0.0666,0.1193,0.0282,0.0428,0.1024,0.0656,0.0481,0.0291,0.0615,0.1447,0.0297,0.0550,0.0732,0.0718,0.0342,0.0279,Vietnam
155,0.0689,0.1188,0.0498,0.0690,0.0642,0.0565,0.0594,0.0325,0.0556,0.1101,0.0546,0.0929,0.0479,0.0383,0.0459,0.0354,Yemen
156,0.0726,0.0983,0.0435,0.0445,0.1253,0.0559,0.0630,0.0264,0.0800,0.0977,0.0426,0.0533,0.0819,0.0542,0.0406,0.0203,Zambia
157,0.0837,0.1134,0.0486,0.0526,0.1134,0.0505,0.0584,0.0272,0.0761,0.1111,0.0383,0.0516,0.0741,0.0436,0.0372,0.0204,Zimbabwe

In [31]:
result.to_csv('mbti_clean.csv', header=True, index=False)

In [32]:
formatted_data.to_csv('mbti_all_type_clean.csv', header=True, index=False)